### ISSUE TITLE
Overlaying workspaces

### ISSUE THREAD

**Issue by bhairavmehta95** [duckietown/duckietown-rosdocker-template#1]
Hi @AleksandarPetrov 

Nice work on this. One thing: as you can see in #aido-containerization, people are starting to run into the same issues of not finding the old duckietown dependencies.

The best way to do this (if you have your own catkin-ws, derived from the original Software repo's one) is by [workspace overlaying](http://wiki.ros.org/catkin/Tutorials/workspace_overlaying). 

We've done this in the ROS baseline as well:
https://github.com/duckietown/challenge-aido1_LF1-baseline-duckietown/blob/v3/Dockerfile#L27

And is documented in 1.7 of the [docs here](https://docs.duckietown.org/DT18/AIDO/out/ros_baseline.html).

You may just want to make your node-ws, by default, overlayed on the catkin-ws of the Software repo (~100% of use cases will need this).

**Comment by AleksandarPetrov** [comment]
@bhairavmehta95, I was considering this option but in the end it seemed to be easier and cleaner if the Software repo nodes are only called and if code has to be reused it's copied here. Copying code is not nice though, but as long as it is not much, it shouldn't be that much of an issue. Especially for education purposes I think that would be better as it would force people to figure out what code and modules they are actually using, how to stack them, and how they actually work. But I can see the downsides as well.

Maybe it would indeed make sense to start from the `duckietown/rpi-duckiebot-base:master18` and use overlaying. I won't have much time these days to change this and test it though, so if you or @selcukercan want to give it a try, please do.

**Comment by bhairavmehta95** [comment]
I think we're implementing a whole new workflow altogether that uses overlayed workspaces and mounting the Software repo - so I'll close this for now.
